# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61bdc95ee171e43c77358d3040e2ebaec58e287d8c1ed230ad58de423a632c245969d88141b81fd8001edfdf6ce19e76e73489a88d4125abc02db6146d7df111

test:
  secret_key_base: 1a8291ccc60ff8fc0fe9be17b094c1fb40c694198f4b56729a42f6b17e09b5b3ca698371501e44350e4751739fa04b22b0178162bfe163e2b323d31dee8ca9c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
